### ISSUE TITLE
Build with MSVC 2010 x64 fails

### ISSUE THREAD

**Issue by AndreasMartin72** [utelle/wxpdfdoc#12]
When building the solution it stops while trying to link against wxWidgets (3.1) libraries.
The x64 static wxWidgets libraries are located at $(WXWIN)\lib\vc_x64_lib\
In wx_win32.bkl WXLIBPATH is initialized by:

>     <set var="WXLIBPATH">
>         <if cond="WX_SHARED=='0'">$(DIRSEP)lib$(DIRSEP)$(COMPILER)$(WXCPU)_lib</if>
>         <if cond="WX_SHARED=='1'">$(DIRSEP)lib$(DIRSEP)$(COMPILER)$(WXCPU)_dll</if>
>     </set>
> 

I changed this for my needs and all worked fine. Perhaps you want to make the differences in you bakefiles...

Best regards,
Andreas

**Comment by utelle** [comment]
Thanks for reporting this issue.

Unfortunately your proposed change to `wx_win32.bl` is not enough to solve the issue. Currently the `bakefile` presets used by wxPdfDocument don't support x64 builds at all. Additionally, `bakefile` doesn't support newer versions of MSVC, unfortunately. The build files for MSVC 2010+ were generated from a `premake` template.

I will try to adopt the approach of wxWidgets for the MSVC 2010+ build files, using property files.

**Comment by utelle** [comment]
The build files were overhauled. There is now a property file `wx_setup.props` which can be used to configure wxWidgets build parameters.

Hopefully, the x64 build now works as expected for MSVC 2010. Please give it a try and let me know the result. Thanks.

**Comment by utelle** [comment]
Configuration names were not correctly identified in x64 builds. This has been fixed in commit 13b7a4706ea93ef2959c20e04fc1327c12142f49.

Reopen if any issue with the new build files remained.
