### ISSUE TITLE
Support for wxRichTextCtrl available?

### ISSUE THREAD

**Issue by mtangoo** [utelle/wxpdfdoc#14]
Can I print the contents of wxRTC? If Yes where do I start?
Thanks for your usual great library.

**Comment by utelle** [comment]
The contents of a `wxRichTextCtrl ` can be printed to PDF via a `wxPdfPrinter` instance. This is demonstrated in the `wxPdfDC` sample application coming with `wxPdfDocument`. Take a look at the method `MyFrame::OnPdfRichTextPrint` in file `printing.cpp` in subfolder `samples/pdfdc`.

Does this answer your question?

**Comment by mtangoo** [comment]
Yes it does!
Thank you for your great work (as usual)!
