### ISSUE TITLE
Question: Any objection to remove all bakefile generated build files?

### ISSUE THREAD

**Issue by utelle** [utelle/wxpdfdoc#17]
Now, after the contribution of a new Unix build system for wxPdfDocument by @vadz, I intend to remove all outdated bakefile generated build files in the near future. 

For Windows platforms build files generated by [premake](https://github.com/premake/premake-core) will be provided. However, `premake5` currently supports only Microsoft Visual Studio 2008-2015 and GNU Make out of the box. Nevertheless, I intend to stick to `premake5`, if possible.

Please comment if you still need the `bakefile` generated build files, or if you would like to see support for other build systems (like those supported by `premake4`).

**Comment by utelle** [comment]
The build system has been overhauled. `bakefile` generated build files were removed and replaced by `premake5` generated build files.

**Comment by mtangoo** [comment]
:+1:
