### ISSUE TITLE
Comctl32 linking error wxWidgets 3.0.2+ wxPdfDocument 0.9.5 + MinGW32 5.3.0/TDM-GCC 5.1.0

### ISSUE THREAD

**Issue by dmitrybg** [utelle/wxpdfdoc#23]
Hello
I am trying to statically link compiled wxPdfDocument library with "hello world" wxWidgets app in Code::Blocks. I get linking errors:

```
C:\Programs\DevTools\wxWidgets-3.0.2\32\lib\gcc_lib\libwxmsw30u_core.a(corelib_app.o):app.cpp|| undefined reference to `InitCommonControls@0'|
C:\Programs\DevTools\wxWidgets-3.0.2\32\lib\gcc_lib\libwxmsw30u_core.a(corelib_app.o):app.cpp|| undefined reference to `OleUninitialize@0'|
C:\Programs\DevTools\wxWidgets-3.0.2\32\lib\gcc_lib\libwxmsw30u_core.a(corelib_app.o):app.cpp:(.text$_Z15wxOleInitializev[__Z15wxOleInitializev]+0x14)||undefined reference to `OleInitialize@4'|
C:\Programs\DevTools\wxWidgets-3.0.2\32\lib\gcc_lib\libwxmsw30u_core.a(corelib_ownerdrw.o):ownerdrw.cpp|| undefined reference to `ImageList_Create@20'|
C:\Programs\DevTools\wxWidgets-3.0.2\32\lib\gcc_lib\libwxmsw30u_core.a(corelib_ownerdrw.o):ownerdrw.cpp|| undefined reference to `ImageList_Add@12'|
C:\Programs\DevTools\wxWidgets-3.0.2\32\lib\gcc_lib\libwxmsw30u_core.a(corelib_ownerdrw.o):ownerdrw.cpp|| undefined reference to 
`ImageList_Draw@24'|
```

and so on. The error happens on 32- and 64-bit compilers (Mingw32 and TDM-GCC-64, respectively).
libcomctl32.a is in place.
Versions of compilers are 5.3.0 and 5.3.1, respectively.
Platform: Windows 7, Code::Blocks 16.01
wzWidgets version 3.0.2, wxPdfDocument version 0.9.5

When linking wxWidgets apps without wxPdfDocument everything is fine.

I've googled a lot on this question, and comctl32-related linking problem had been reported, but looks it is not the case, because without wxPdfDocument everything works fine.

Any suggestions?
Thanks!

**Comment by vadz** [comment]
What do you mean by "in place"? Do you link with this library or not? Because it certainly looks like you don't...

**Comment by dmitrybg** [comment]
Sorry, it turned out that problem is not related to wxPdfDocument
