### ISSUE TITLE
Can't check if SaveAsFile was successful

### ISSUE THREAD

**Issue by wh11204** [utelle/wxpdfdoc#26]
Method wxPdfDocument::SaveAsFile() can fail (for example, trying to overwrite an open file), but it can't be checked. Also, wxWidgets mandates checking IsOk() before using a wxFileOutputStream.

I have attached a patch changing the return value of SaveAsFile() from void to bool and returning true if the operation was successful. Also, you get rid of the annoying wxLog message.

[saveasfile.txt](https://github.com/utelle/wxpdfdoc/files/879025/saveasfile.txt)

**Comment by utelle** [comment]
Thanks for supplying this patch. I applied it (only slightly modified to match my coding style).
