### ISSUE TITLE
Image Handler errors using simple markup language

### ISSUE THREAD

**Issue by gunamoi1** [utelle/wxpdfdoc#33]
Errors are reported when using an <img> element in the simple xml version of wxPDFDocument.

Mods are required because of a bug in wxPdfDocument::GetImageSize().
The function declaration has the second parameter "mimeType", but calls to this function in pdfxml do not use the second parameter.
So its value defaults to empty string, which causes error messages in the line:
  wxImage image(file, mimeType);
Because wxImage will fail to find a handler for mimeType="".

For example, four related error messages occur when running the sample program "minimal" to generate the markup example document "xmlwrite.pdf".
****************************
Solution:
To avoid issues with any other derived software, the following minimal changes 
to Function wxPdfDocument::GetImageSize(), are proposed.

-in pdfdocument.cpp, line 1635 currently:
  wxImage image(file, mimeType);

-replace it with the following lines:
   wxImage image;
   if (mimeType.IsEmpty())
      image.LoadFile(file);//allows wxImage to try and autodetect image type
   else
      image.LoadFile(file, mimeType);//as per original mimetype version

With these changes, the sample "minimal" produces the markup example without any errors being generated.
This was tested with wxWidgets 3.0.3

regards,
Garry.

**Comment by utelle** [comment]
Hi Garry,

thanks for reporting the issue. I applied your proposed solution.

Regards,

Ulrich
