### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by mael15** [utelle/wxpdfdoc#34]
When I use L"≤ " in wxWidgets, I can see this special char in my program, but I get a "?" in the pdf. what can I do?

**Comment by utelle** [comment]
If you use a character constant like L"≤" in your source code, this can already be the cause of the problem. It will depend on the encoding of your source files whether this will work or not. That is, the first step is to make sure that target wxString object contains the correct Unicode representation (U+2264) of this special character.

To output special characters to PDF requires to use a font that contains those special characters. This is usually not the case for the PDF core fonts Courier, Helvetica, and Times Roman. That is, you will have to register an appropriate Unicode Truetype font to accomplish this.

Please keep in mind that `wxPdfDocument` uses `Arial` as an alias name for `Helvetica`. That is, using font `Arial` without explicitly registering the font with method `RegisterFont` of the `wxPdfFontManager` will use the PDF core font `Helvetica` which does not contain the special character "less equal".

If the special character is correctly displayed on screen, you may register the `wxFont` instance used for screen display with method `RegisterFont` of the `wxPdfFontManager` and select that font in your `wxPdfDocument` instance.

**Comment by mael15** [comment]
Great, thank you, works!
For everyone else with the same problem:
wxFont defaultFont(wxFontInfo(10).Family(wxFONTFAMILY_DEFAULT).Underlined(false));
wxPdfFont pdfArialFont = wxPdfFontManager::GetFontManager()->RegisterFont(defaultFont, wxT("Arial"));
bool ok = pdfDcmt.SetFont(pdfArialFont);
