### ISSUE TITLE
How to insert a a large image into a page?

### ISSUE THREAD

**Issue by kipade** [utelle/wxpdfdoc#38]
Or, how to convert a large image using the code?
I followed the tutourals, coding like:

wxPdfDocument pdf;
pdf.AddPage();
pdf.Image(wxS("smile.jpg"), 0, 0, 14043, 9933);
pdf.SaveAsFile("test.pdf");

got a large pdf file, but can not find the image.
Thanks.

**Comment by kipade** [comment]
Im sorry, i found the resolution soon. I just pass size to ctor of wxPdfDocument.
Regards,

**Comment by utelle** [comment]
Looking at your sample code `pdf.Image(wxS("smile.jpg"), 0, 0, 14043, 9933);`, I suspect that _just passing the size to the ctor of wxPdfDocument_ is the right approach. I assume you have a high resolution graphics file and you tried to pass its width (14043) and height (9933) in pixels to the width and height parameters of the `Image` method. However, wxPdfDocument expects the values of width and height in user units (wxPdfDocument's default is _millimeter_). That is, in your code the image has a dimension of approximately 14 meter x 10 meter, while the default paper size is DIN A4 (21 cm x 29.7 cm). So only a really extremely small fraction of your graphic (0.04 %) will be visible on the page.

As the width and height you have to specify the area on the resulting PDF page in which the graphic should be displayed - in millimeter, if you stay with the default units. wxPdfDocument will then scale the graphic accordingly.
