### ISSUE TITLE
Uninitialized variable in wxPdfPrinter

### ISSUE THREAD

**Issue by k4martin** [utelle/wxpdfdoc#45]
The m_showProgressDialog member of wxPdfPrinter is left uninitialized in the constructor. This is causing inconsistent behaviour whether or not a progress dialog is shown while the PDF is generated, unless it is set explicitly by calling wxPdfPrinter::ShowProgressDialog.

**Comment by utelle** [comment]
Thanks for reporting.

Commit c48bc610c6db8195805ce449fef5bcd852f598b5 fixes the issue.
