### ISSUE TITLE
WriteXML: Text position after rendering table

### ISSUE THREAD

**Issue by dschmeer** [utelle/wxpdfdoc#46]
If I define a table and following text like this:
```
<table border="1" cellpadding="0">
	<colgroup>
		<col width="40"/>
		<col width="40"/>
	</colgroup>
	<tbody>
		<tr>
			<td>ABC</td>
			<td>DEF</td>
		</tr>
		<tr>
			<td>GHI</td>
			<td>JKL</td>
		</tr>
	</tbody>
</table>
STU
<br/>
VWX
```
It looks like that:
![image](https://user-images.githubusercontent.com/43547563/45964330-ce2a4600-c025-11e8-8c23-27cf48e39c55.png)
Notice the text "STU" starting within the table instead of below.
This could be fixed by putting in "`<br/>`" after the table, but when using cellpadding you are out of luck:
```
<table border="1" cellpadding="6">
	<colgroup>
		<col width="40"/>
		<col width="40"/>
	</colgroup>
	<tbody>
		<tr>
			<td>ABC</td>
			<td>DEF</td>
		</tr>
		<tr>
			<td>GHI</td>
			<td>JKL</td>
		</tr>
	</tbody>
</table>
STU
<br/>
VWX
```
![image](https://user-images.githubusercontent.com/43547563/45965576-257de580-c029-11e8-887a-858b9271feba.png)
I would have expected the text "STU" to always start right below the table, on the left.
By putting in `m_document->SetXY(saveLeftMargin, y);` right before the end of the function wxPdfTable::Write(), it does what I'd expect.

Can this be changed?

Regards

Dieter

**Comment by utelle** [comment]
Obviously an oversight on my side. Of course the current position should be updated accordingly after a table has been written. Thanks for reporting this issue.

The latest commit a2b100f16619b08678dc6391547de8e9e83ebceb should fix this problem.

**Comment by utelle** [comment]
After 6 weeks without complaints about the fix, it seems fair to assume that this issue can be closed.
