### ISSUE TITLE
write xml with row span

### ISSUE THREAD

**Issue by icryrainix** [utelle/wxpdfdoc#59]
This library is absolutely fantastic.
I am trying to use it to generate pdf document, with write xml function, I can easily create table, but if the table with row span on multiple pages(page break), it looks a little ugly, see the picture.
![result](https://user-images.githubusercontent.com/5716088/61794773-767e8600-ae54-11e9-9bbd-9f499d091c32.png)
How can I fix it? possible to let this row start from new page?
Thank you very much.

**Comment by utelle** [comment]
Without seeing the XML code used for creating the table it is a bit difficult to analyze whether there is a chance to avoid or fix the problem.

Could you provide a sample XML I can use for testing? You could send it via private mail.

**Comment by icryrainix** [comment]
Thank you very much for your quick response.

I send source code with xml script and the pdf file generated, please kindly find the attached.

Best,
Nix

**Comment by icryrainix** [comment]
Nix Ni would like to recall the message, "[utelle/wxpdfdoc] write xml with row span (#59)".

**Comment by icryrainix** [comment]
I send the code and pdf file to this email box: github@telle-online.de

**Comment by utelle** [comment]
I received your mail, and I will take a look at this issue within the next few days.

**Comment by utelle** [comment]
Commit 5c01a32a0188a8b1188d1daab131569b23394abb hopefully fixes your issue. Rows of an XML table that are affected by common row spans are now kept together on the same page.

Please give it a try.

**Comment by icryrainix** [comment]
Yes, it's OK now, thanks a lot.

**Comment by icryrainix** [comment]
Hi,

While we are using wxpdfdoc in our project, we found an issue, could you please help us on this?

I have attached the xml and pdf.

Thank and regards.

From: Nix Ni<mailto:nixingbiao@outlook.com>
Sent: 2019年7月25日 9:32
To: utelle/wxpdfdoc<mailto:reply@reply.github.com>; utelle/wxpdfdoc<mailto:wxpdfdoc@noreply.github.com>
Cc: Nix Ni<mailto:nixingbiao@outlook.com>; Author<mailto:author@noreply.github.com>
Subject: RE: [utelle/wxpdfdoc] write xml with row span (#59)

Thank you very much for your quick response.

I send source code with xml script and the pdf file generated, please kindly find the attached.

Best,
Nix

**Comment by icryrainix** [comment]
I tried with different font size, it font size is a little bigger and the content will display in two pages, the format will be wrong.

Please kindly find the document attached.

Best regards,
Nix

From: Nix Ni<mailto:nixingbiao@outlook.com>
Sent: 2020年3月20日 11:07
To: utelle/wxpdfdoc<mailto:reply@reply.github.com>; utelle/wxpdfdoc<mailto:wxpdfdoc@noreply.github.com>
Cc: Author<mailto:author@noreply.github.com>
Subject: RE: [utelle/wxpdfdoc] write xml with row span (#59)

Hi,

While we are using wxpdfdoc in our project, we found an issue, could you please help us on this?

I have attached the xml and pdf.

Thank and regards.

From: Nix Ni<mailto:nixingbiao@outlook.com>
Sent: 2019年7月25日 9:32
To: utelle/wxpdfdoc<mailto:reply@reply.github.com>; utelle/wxpdfdoc<mailto:wxpdfdoc@noreply.github.com>
Cc: Nix Ni<mailto:nixingbiao@outlook.com>; Author<mailto:author@noreply.github.com>
Subject: RE: [utelle/wxpdfdoc] write xml with row span (#59)

Thank you very much for your quick response.

I send source code with xml script and the pdf file generated, please kindly find the attached.

Best,
Nix

**Comment by utelle** [comment]
> I tried with different font size, if font size is a little bigger and the content will display in two pages, the format will be wrong.

If the font size is increased, then the column containing the long enumeration increases in height due to additional automatic line breaks. And this can cause layout problems.

One rule of the XML feature is that the content of a table cell has to fit on the remaining part of a page. Additionally, wxPdfDocument has an automatic page break mechanism, if output occurs below a certain page bottom margin.

The default page break margin is 20 mm from the page bottom. This page break margin can be changed. It is also possible to turn off the automatic page break feature.

For your use case, I would recommend to call
```C++
pdf.SetAutoPageBreak(false);
```
right at the beginning. For XML output this is usually the best approach.

However, if the content of a table cell is higher than the page height, you will still experience a page break, but only once. After the page break, the cell content not fitting on the page will not be shown at all.
