### ISSUE TITLE
wxBrush alpha used for text, not changable

### ISSUE THREAD

**Issue by mael15** [utelle/wxpdfdoc#61]
in template mode, when you set alpha in a brush, this also sets alpha for text and it appears not to be reversable. EDIT: only if you draw something, the text after drawing is opaque again:
	wxSize dcSize = dc->GetSize();

	wxFont fnt;
	fnt.SetFractionalPointSize(dcSize.GetWidth() * 0.03);
	dc->SetFont(fnt);

	dc->DrawText(_("no transparency"), dcSize.x * 0.1, dcSize.y * 0.1);
	dc->SetBrush(wxColour(255, 0, 0, 25));
	dc->DrawCircle(dcSize.x * 0.3, dcSize.y * 0.5, dcSize.GetWidth() * 0.1);
	dc->SetBrush(wxColour(0, 255, 0, 25));
	dc->DrawCircle(dcSize.x * 0.7, dcSize.y * 0.5, dcSize.GetWidth() * 0.1);
	dc->DrawText(_("now transparent"), dcSize.x * 0.1, dcSize.y * 0.2);
	dc->SetBrush(wxColour(0, 0, 0, wxALPHA_OPAQUE));
	dc->DrawText(_("still transparent"), dcSize.x * 0.1, dcSize.y * 0.3);
	dc->SetTextForeground(wxColour(0, 0, 255, wxALPHA_OPAQUE));
	dc->DrawText(_("seems unchangable"), dcSize.x * 0.1, dcSize.y * 0.4);

	dc->DrawCircle(dcSize.x * 0.7, dcSize.y * 0.8, dcSize.GetWidth() * 0.1);
	dc->DrawText(_("now it is opaque again"), dcSize.x * 0.1, dcSize.y * 0.5);

**Comment by mael15** [comment]
yes, this particular problem is gone. But, as you can see here, the text itself cannot be transparent in the pdf:


	wxSize dcSize = dc->GetSize();

	wxFont fnt;
	fnt.SetFractionalPointSize(dcSize.GetWidth() * 0.03);
	dc->SetFont(fnt);
	dc->SetPen(*wxBLACK_PEN);

	dc->SetTextForeground(wxColour(0, 0, 255, wxALPHA_OPAQUE));
	dc->DrawText(_("no transparency"), dcSize.x * 0.1, dcSize.y * 0.1);
	dc->SetBrush(wxColour(255, 0, 0, wxALPHA_OPAQUE));
	dc->DrawCircle(dcSize.x * 0.3, dcSize.y * 0.5, dcSize.GetWidth() * 0.1);

	dc->SetTextForeground(wxColour(0, 0, 255, 125));
	dc->DrawText(_("50% transparent"), dcSize.x * 0.1, dcSize.y * 0.3);
	dc->SetBrush(wxColour(255, 0, 0, 125));
	dc->DrawCircle(dcSize.x * 0.4, dcSize.y * 0.5, dcSize.GetWidth() * 0.1);

**Comment by utelle** [comment]
I made a few experiments myself, and as far as I can tell, transparency is applied to text objects as well. However, the default PDF transparency model is most likely different than that used on screen. Therefore results might be different than expected.

Regarding the default pen wxPdfDC initially sets a black pen, if used in default mode. However, in template mode no defaults are applied. That is, in template mode your application is responsible for initializing pen and brush. This decision was made on purpose, although it is of course debatable.

**Comment by utelle** [comment]
In the meantime I tested the sample code as given by you. One thing your application maybe has to take care of, is to set `wxDC::SetBackgroundMode(wxPENSTYLE_TRANSPARENT)`, so that text is drawn without a background color. Alternatively you have to specify a text background color with the intended transparency - I adjusted the **wxPdfDC** code to respect the alpha value of the text background color (see commit ed5dd19ade74f59d570f7bd29e04993b9e19baee).

From my point of view the issue should now be solved, and I intend to close it, unless you can provide evidence that the issue still requires further attention.

**Comment by utelle** [comment]
Closing ... reopen if necessary.
