### ISSUE TITLE
Memory access violation in wxPdfTable::SetCellDimensions

### ISSUE THREAD

**Issue by mxdamien** [utelle/wxpdfdoc#62]
Hi !

We encountered a problem with the current wxPdfDoc Master introduced with 48af68eb8aca7749285750d00ccd8f86e531fd47.
We get an access violation when creating PDFs using XML-templates, due to an underflow of the row index variable "row" in wxPdfTable::SetCellDimensions(double maxWidth) at pdfxml.cpp L 429, which leads to memory overflow.

The issue can be triggered by running the wxPdfDoc "markup" example (Group 3, Sample 5 of the minimal examples)

**Debugging:**

Starting debugging at pdfxml.cpp L 613

pdfxml.cpp L 613 : int row = 0

pdfxml.cpp L 665 (PrepareXmlTable)  : table->SetBodyRowFirst(row)     

--> m_bodyRowFirst = 0 .... This will always be 0 since this is the only call to SetBodyRowFirst ever, there is also never direct access to m_bodyRowFirst and row is 0 as initialized in L 613

pdfxml.cpp L 789 (PrepareXmlTable)  : table->SetCellDimension(maxWidth)

pdfxml.cpp L 388 (SetCellDimension) : row = m_bodyRowFirst

--> row = 0          

pdfxml.cpp L 419 (SetCellDimension) : row < nextRow - 1             

--> row = 0 , nextRow = 1 --> (row < nextRow - 1) = false - so we enter the else branch

pdfxml.cpp L 427 (SetCellDimension) : for loop : for (row = nextRow - 2; row >= firstRow; --row)          

--> row = 1 - 2 = 4294967295 (underflow to max unsigned int) and so the for loop condition currRow >= firstRow is true [4294967295 >= 1]. 

Row is counting backwards without limitation from max unsigned int, which leads to an access violation when accessing m_maxHeights[4273576331] at L 429 due to Memory overflow after creating 21390964 hash map entries in m_maxHeights.

Regards,

David

**Comment by utelle** [comment]
Thanks for reporting this bug.

Commit e34ce362b235f1e8fce6a6316c0119b836285d35 should fix the issue. Please give it a try.

**Comment by mxdamien** [comment]
Fix confirmed. Works fine.
Thanks for the quick fix !
