### ISSUE TITLE
 wxPdfEncrypt::Encrypt(int n, int g, wxString& str) don't work when a character of str is not representable with a single byte

### ISSUE THREAD

**Issue by stkruse** [utelle/wxpdfdoc#64]
Hello,
` wxPdfEncrypt::Encrypt(int n, int g, wxString& str)` doesn't work when a character of str is not representable with a single byte.
This can be reproduced trying to encrypt "Привет мир".

This is, because wxWidgets tries to cast in an intelligent way and overloads  `operator unsigned char()`

I attached a patch fixing this issue. The file is a txt file, since github doesn't allow .patch file extensions...
[pdfencrypt.txt](https://github.com/utelle/wxpdfdoc/files/3916224/pdfencrypt.txt)

Best regards

**Comment by stkruse** [comment]
I made a pull request with the fix:  #65 
I adjusted the fix to not use the auto keyword to be consistent to the rest of wxPdfDoc.

**Comment by utelle** [comment]
For the use within wxPdfDocument itself the implementation of `Encrypt` is sufficient. However, for the generic use case it is broken, I have to admit. IMHO the best approach will be to convert the given string to UTF-8 before processing it further.

**Comment by utelle** [comment]
Closing, because the issue won't be fixed in wxPdfDocument (and is a _no issue_ for internal wxPdfDocument processing). For further details see discussion in PR #65.
