### ISSUE TITLE
Compile wxPdfDoc in Unicode Mode with UTF8 under OS Windows

### ISSUE THREAD

**Issue by DarthAlSith** [utelle/wxpdfdoc#67]
Goodmorning everyone.
Sorry for my absence, but I had been momentarily moved to something else.
I started working on the UTF8 project for which I had opened previous task #66 ; I downloaded wxWidgets-3.1.3 and wxPdfDoc-0.9.8.

I compiled the wxWidgets with the command:
nmake -f makefile.vc SHARED=1 MONOLITHIC=1 BUILD=DEBUG, after manually adding in the config.vc file the forcing for the CPPFLAGS /DwxUSE_UNICODE_UTF8=1.

Now, I have no idea how to compile the wxpdfdoc .. can you help me .. ??

**Comment by utelle** [comment]
wxPdfDocument comes with solution files for various VC++ versions. So the easiest approach would be to open the solution file matching your Visual Studio version, to adjust the precompiler settings by adding the symbol `wxUSE_UNICODE_UTF8=1`, and then to build the configuration you want to use for your application(s).

**Comment by utelle** [comment]
Sorry, I didn't spot that you use the monolithic wxWidgets build. The current solution files support the typical DLL build of wxWidgets only. You have to regenerate the build files using premake5 with appropriate options.

**Comment by DarthAlSith** [comment]
I'm trying to compile with VS and I'm trying to go down the errors.. 
Because, however, I need to realize an automatic shell procedure, could you guide me in using premake5 to obtain it..?

**Comment by utelle** [comment]
The latest **premake5** version can be downloaded from [premake5 releases](https://github.com/premake/premake-core/releases). This tool allows to generate Visual Studio solution files. The premake5 script (premake5.lua) coming with wxPdfDocument references a property file [wx_setup.props](https://github.com/utelle/wxpdfdoc/blob/master/build/wx_setup.props) which allows to adjust certain project settings (like wxWidgets version). This file has to be accessible in the build directory.

**premake5** is invoked from the root directory of wxPdfDocument like the following
```
premake5 vs2015 --monolithic [--builddir=your-build-dir]
```
where `vs2015` should be replaced by the Visual Studio version you are using (suppoerted are `vs2010`,`vs2012`,`vs2013`,`vs2015`,`vs2017`, and `vs2019`). Specifying a build directory is optional, but recommended to not interfer with the build files coming with wxPdfDocument.

**msbuild** can be used to build wxPdfDocument from the command line - see file [appveyor.bat](https://github.com/utelle/wxpdfdoc/blob/master/admin/appveyor/appveyor.bat) how this can be done; [.appveyor.yml](https://github.com/utelle/wxpdfdoc/blob/master/.appveyor.yml) shows you how some of the parameters are set.

**Comment by DarthAlSith** [comment]
Thank you very much.
In the end I managed to launch the premake5 .. I missed the passage 'MsBuild'.

I'm going to try tha automation and update you. ;)

**Comment by DarthAlSith** [comment]
Hi.
If I compile wxpdfdoc as a static library (from visual studio solution or with msbuild command) it is fine, but when I try to compile it as a dynamic library (which is the configuration I need) it ends with some errors LNK2001 unresolved symbols.

I connected all * .lib created during the compilation of wxWidgets-3.1.3 as dll, but the errors persist .. could you suggest me some attempt..??

**Comment by utelle** [comment]
Without seeing which symbols are unresolved it is impossible to tell what might have gone wrong.

Since you said you built wxWidgets as monolithic, this could possibly be the cause. I have to admit that I never tested the monolithic configuration myself, because I use the default DLL configuration for my own projects. For the monolithic build it should be sufficient to link against the single monolithic link library.

**Comment by DarthAlSith** [comment]
Sorry. ...I had forgotten the include of some necessary static libraries.

Now, the only problems that seem to persist are:

> error C2440: 'initializing' : cannot convert from 'const char [15]' to 'const wxChar *'

I have the impression that some options are missing for the compilation and having forced wxUSE_UNICODE_UTF8 = 1 generates an error .. any ideas?

**Comment by utelle** [comment]
My guess is that you have to change the use of macro `wxS` in the string initialization to macro `wxT` in the affected files.

**Comment by DarthAlSith** [comment]
It was my suspicion .. and I wanted to avoid it ..

I'm leaving the office .. I'm trying this way tomorrow in the morning. I update you

**Comment by DarthAlSith** [comment]
Ok. By replacing the define I was able to compile the dynamic library; as soon as I can fix my application I do tests.
I update you.
Thank you.

**Comment by utelle** [comment]
Yes, please keep me updated.

When I changed the use of macro `wxT` to macro `wxS` throughout the code of wxPdfDocument, I had the best intentions, but I was unfortunately not aware of the consequences for the UTF8 build, because it is not the default build and seems to be used only by a rather small number of developers. However, I will try to make a future release of wxPdfDocument compatible.

**Comment by DarthAlSith** [comment]
Hi utelle,

I need your help. I've to create a makefile for nmake to build wxpdfdoc for OS Windows.. I saw that you, in the 0.9.3 version, used bakefile program; I read the documentation but I'm not able to realize what I need.. could you help me?

**Comment by utelle** [comment]
I haven't used `bakefile` for ages anymore, and as far as I know it doesn't support the creation of `nmake` makefiles anyway.

Currently I use `premake5` to generate solution files for Visual C++. Unfortunately `premake5` doesn't support the creation of `nmake` makefiles either.

However, you may invoke `msbuild` from the command prompt to build a certain solution. Maybe this is an option for you. How this work, can be seen in the [AppVeyor script](https://github.com/utelle/wxpdfdoc/blob/master/admin/appveyor/appveyor.bat) used for Continuous Integration testing.

**Comment by utelle** [comment]
In the course of commit 72e61abaa7efb7fbabd66c8b344f99da71b2d384 I also tried to address your issue with compiling in UTF-8 mode under Windows. Following a recommendation of @vadz I replaced the use of  `wxChar` by `wxStringCharType`. This should work well together with string macro `wxS`.

I have not tested UTF-8 mode myself, so please give it a try and report back any further issues. Thanks.

**Comment by DarthAlSith** [comment]
Hi.
Me and my team leaved the project..so this task can be closed
