### ISSUE TITLE
horizonal line influenced by previous drawing

### ISSUE THREAD

**Issue by mael15** [utelle/wxpdfdoc#68]
please see this image, the issue is only about the horizonal lines with the number 10 on both sides, ignore all other differences.
https://drive.google.com/file/d/1_LUjD9RjRsGNADBK21HigROtASwScg4w/view?usp=sharing
i draw these two regions of circles next to each other with the same code. the first two on top is how they look in my app, the next four are from a pdf, the left one is drawn before the right one. as you can see, the horizonal line is different depending on what has been drawn before. as you can see on the top two, the horizonal lines are fine when drawing in my app on a wxMemoryDC, the problem occurs only when creating pdfs using wxPdfDC.
I hope I could explain it good enough... 
It might be quite time consuming to create a minimal example, I am hoping someone might have an idea without it.
I use today´s git master branch on Windows 10 with a debug x64 compilation.

**Comment by utelle** [comment]
Sorry, without seeing any code it is impossible to guess what is going wrong. It is very strange that only horizontal lines are affected. If there is a general transformation problem, I would expect a displacement of the vertical lines, too, but that doesn't seem to be the case.

If possible, please provide a small sample application (or at least code snippets of the drawing code) reproducing the problem. Then I will look into it. Additionally, let me know which wxWidgets version you are using.

**Comment by mael15** [comment]
Sorry, there is no issue. While trying to make a minimal example I realized my coding error. I should have known, it was too weird.

**Comment by utelle** [comment]
I'm glad to hear that you were able to solve your problem.
