### ISSUE TITLE
g++ warnings from pdfcjkfontdata.inc

### ISSUE THREAD

**Issue by bje-** [utelle/wxpdfdoc#69]
G++ produces warnings like so when compiling `pdffontmanager.cpp` with `-Wall`:
```
pdfcjkfontdata.inc:117:14: warning: ‘cwPMincho’ defined but not used [-Wunused-variable]
```

Some fonts are disabled in `pdfcjkfontdata.inc` due to this comment:
```
        // These M$ fonts don't work cross platform.
```

These entries refer to the following static arrays in that same file: `cwPGothic`, `cwUIGothic` and `cwPMincho`. I suggest it would be acceptable to similarly disable these arrays with `#if 0` guards around them to silence such warnings. If so, I will submit a pull request.

**Comment by utelle** [comment]
Commit bf355c71c49875dad121750b326d385d6ec03cdd should fix the issue.

I added a preprocessor symbol, `WXPDFDOC_ENABLE_CJK_MS_FONTS`, so that a user of the library can decide whether to enable support for those fonts or not.

**Comment by bje-** [comment]
That's great, thanks! 34 minutes from bug report to patch. :+1:
