### ISSUE TITLE
Avoid Symlinking

### ISSUE THREAD

**Issue by DarthAlSith** [utelle/wxpdfdoc#75]
Hi Staff,

I compile pdfdoc under Linux OS, making the dynamic library and all works fine.

After creating the library, the make istructions generate the main file "libwxcode_%_.so.0.0.0" and 2 symbolic link "libwxcode_%_.so.0" and "libwxcode_%_.so".. I want to generate, automaticly, a single library called "libwxcode_%_.so"
I analized the script but I'm not able to find a way to avoid.. could you help me..??

**Comment by utelle** [comment]
For Linux the wxPdfDocument build process is based on [_libtool_](https://www.gnu.org/software/libtool/manual/). So please check the _libtool_ documentation. And maybe @vadz (who contributed the Linux build support) can give further advice.

**Comment by vadz** [comment]
I don't understand the problem, i.e. why would anybody bothered by the existence of the symlinks. You do already have a "single library". IMO this should be just closed.

**Comment by DarthAlSith** [comment]
thank you guys.
looking for in libtool script, I've found how to obtain my goal.
