### ISSUE TITLE
Compilation Error with latest wxWidgets 3.1.5

### ISSUE THREAD

**Issue by MaxGaspa** [utelle/wxpdfdoc#77]
Dear utelle,

Using

Win10
Msys2 with MinGW64 (GCC 10.2)
wxPdfDocument 0.9.8 sources downloaded on 2020 Oct 10th

and 

mingw32-make -f makefile  CXXFLAGS="-std=c++11 -pipe -mthreads -fexceptions -fpermissive -Wno-attributes -Wno-deprecated-declarations -O2" config=release_win64 clean

mingw32-make -f makefile  CXXFLAGS="-std=c++11 -pipe -mthreads -fexceptions -fpermissive -Wno-attributes -Wno-deprecated-declarations -O2" config=release_win64 wxpdfdoc

I got the following compilation error related to wxRound overloading

pdfdc.cpp
In file included from ../src/pdfdc.cpp:25:
../src/pdfdc29.inc: In member function 'virtual void wxPdfDCImpl::DoDrawRotatedText(const wxString&, wxCoord, wxCoord, double)':
../src/pdfdc29.inc:1070:107: error: call of overloaded 'wxRound(size_t)' is ambiguous
 1070 |       m_pdfDocument->Rect(ScaleLogicalToPdfX(x), ScaleLogicalToPdfY(originalY + wxRound(lineNum*heightLine)), ScaleLogicalToPdfXRel(w), ScaleLogicalToPdfYRel(h), wxPDF_STYLE_FILL);
      |                                                                                                           ^
In file included from c:\msys64\usr\local\wxMSW-3.1.5/include/wx/event.h:18,
                 from c:\msys64\usr\local\wxMSW-3.1.5/include/wx/wx.h:24,
                 from ../src/pdfdc.cpp:20:
c:\msys64\usr\local\wxMSW-3.1.5/include/wx/math.h:137:12: note: candidate: 'int wxRound(double)'
  137 | inline int wxRound(double x)
      |            ^~~~~~~
c:\msys64\usr\local\wxMSW-3.1.5/include/wx/math.h:151:12: note: candidate: 'int wxRound(float)'
  151 | inline int wxRound(float x)
      |            ^~~~~~~
c:\msys64\usr\local\wxMSW-3.1.5/include/wx/math.h:165:12: note: candidate: 'int wxRound(long double)'
  165 | inline int wxRound(long double x) { return wxRound(double(x)); }
      |            ^~~~~~~
mingw32-make[1]: *** [wxpdfdoc_mono.make:304: obj/gcc/Win64/Release/wxpdfdoc/pdfdc.o] Error 1
mingw32-make: *** [makefile:110: wxpdfdoc] Error 2

The same sources were compiled successfully with WxWidgets 3.1.4

Please note that I'm using

WXWIN_COMPATIBILITY_3_0 set to zero

Hope this helps

Max

**Comment by utelle** [comment]
This is the same problem as in issue #72 and was fixed in commit 5d72f9c4d08f10ce33fd726551acc298694d783c.

Please download the latest source code version from the [master branch](https://github.com/utelle/wxpdfdoc).

**Comment by MaxGaspa** [comment]
Yes, using the latest sources compilation is successfully.

Thank you and apologize for wasting your time....

Max
