### ISSUE TITLE
wrap cell across page

### ISSUE THREAD

**Issue by icryrainix** [utelle/wxpdfdoc#88]
This is a gread job, thanks.
Is it possible to wrap cell across pages in xml table? Something like this:
![1](https://github.com/utelle/wxpdfdoc/assets/5716088/b5387402-d8a7-4ce9-872a-ef9f92c8083b)

**Comment by utelle** [comment]
> Is it possible to wrap cell across pages in xml table?

Plain and simple answer: **_no_**. This is not possible with the current implementation. All cells of a table row must fit into the remaining space on a page, otherwise the whole row will be forwarded to the next page.

**Comment by utelle** [comment]
Since I do not plan to add such a feature, I'm going to close this issue. Please feel free to re-open it, if you think you have good arguments that such a feature would be of general interest.

**Comment by icryrainix** [comment]
Got it, thanks. Sometimes, one page does not have enough space to fit all.

**Comment by utelle** [comment]
> Sometimes, one page does not have enough space to fit all.

Well, that is indeed a use case that is not covered by the current implementation. However, I still don't intend to add a feature to automatically split a table row across page breakes, but if you or any other user of the component comes up with a reasonable implementation handling this use case, I will consider to integrate it.
