### ISSUE TITLE
rotated text at wrong position (bounty)

### ISSUE THREAD

**Issue by pele65** [utelle/wxpdfdoc#92]
Dear team wxPdfDocument,
I'm using your software to save maps as pdf files.
From time to time I find wrong texts in a pdf.
It's always a rotated text which should not be visible because it's outside the shown area.
You can see the problem in the appended pdfs: 
Ankommensplan_Rahmen.pdf shows the whole thing with all streetnames properly drawn.
Ankommensplan_Fehler.pdf shows a part of it and one streetname is falsely shown 
('Salierstraße', near the upper left corner).
The rotation angle seems to be correct, but it should be placed a lot more to the right and upwards, outside the shown area.
The problem occurs randomly, I mean with unforseeable areas and texts.
Once it appears, it shows up every time of course with this map and area.

The appended pdfs are part of a voluneer work, which I'm not paid for.
As I use wxPdfDocument for paid work also, I could pay for a solution.
It would be easier for me to pay a normal bill than to donate some money, because of tax reasons.
I'd prefer personal mail for further detail to this point. 
(As I'm a german native speaker, it would be easier in german language, if you are a native german speaker too.)
I'm not sure how I can give you a working minimal example, as the circumstances showing the problem are not clear.
One idea is, to create a kind of LoggingDC which generates code to fill a wxDC.
This would be an amount of work of course, so I would start it only after your feedback to this idea.

Samples:
[Ankommensplan_Rahmen.pdf](https://github.com/utelle/wxpdfdoc/files/14013199/Ankommensplan_Rahmen.pdf)
[Ankommensplan_Fehler.pdf](https://github.com/utelle/wxpdfdoc/files/14013200/Ankommensplan_Fehler.pdf)

And by the way: I appreciate wxPdfDocument very much, 
it's a great part of software and it helps me a lot!
Best wishes!
Peter

**Comment by utelle** [comment]
> I'm using your software to save maps as pdf files.

Which version of wxWidgets and wxPdfDocument are you using? Which platform(s)?

> From time to time I find wrong texts in a pdf. It's always a rotated text which should not be visible because it's outside the shown area.

Do you specify clipping regions to prevent drawing operations outside of certain regions?

> You can see the problem in the appended pdfs: Ankommensplan_Rahmen.pdf shows the whole thing with all streetnames properly drawn. Ankommensplan_Fehler.pdf shows a part of it and one streetname is falsely shown ('Salierstraße', near the upper left corner). The rotation angle seems to be correct, but it should be placed a lot more to the right and upwards, outside the shown area.

Could be a miscalculation of coordinates. However, without seeing the code that was used to create the map and the text it is hard to tell, what goes wrong.

> The problem occurs randomly, I mean with unforseeable areas and texts. Once it appears, it shows up every time of course with this map and area.

Well, intermittent faults can be really hard to diagnose.

> The appended pdfs are part of a voluneer work, which I'm not paid for. As I use wxPdfDocument for paid work also, I could pay for a solution. It would be easier for me to pay a normal bill than to donate some money, because of tax reasons.

Understandable. We can discuss details via personal mail.

> I'd prefer personal mail for further detail to this point.

You can find my personal mail address at the end of the _version history_ section of the [wxPdfDocument documentation](https://utelle.github.io/wxpdfdoc/docs/html/index.html) website or you can use the mail address given on my [GitHub profile](https://github.com/utelle)

> (As I'm a german native speaker, it would be easier in german language, if you are a native german speaker too.)

Yes, I'm German and you can write me a mail in German, of course.

> I'm not sure how I can give you a working minimal example, as the circumstances showing the problem are not clear. One idea is, to create a kind of LoggingDC which generates code to fill a wxDC. This would be an amount of work of course, so I would start it only after your feedback to this idea.

Let's discuss this via personal mail.

**Comment by utelle** [comment]
[Release 1.1.0](https://github.com/utelle/wxpdfdoc/releases/tag/v1.1.0) fixes the problems.
